#ifndef MINISQL_DBERR_H
#define MINISQL_DBERR_H

enum dberr_t {
  DB_SUCCESS = 0,
  DB_FAILED,//1
  DB_ALREADY_EXIST,//2
  DB_NOT_EXIST,//3
  DB_TABLE_ALREADY_EXIST,//4
  DB_TABLE_NOT_EXIST,//5
  DB_INDEX_ALREADY_EXIST,//6
  DB_INDEX_NOT_FOUND,//7
  DB_COLUMN_NAME_NOT_EXIST,//8
  DB_KEY_NOT_FOUND,//9
  DB_QUIT//10
};

#endif  // MINISQL_DBERR_H
